# 🔐 RAILWAY SECRETS CHECKLIST
# Copy these EXACT variable names to Railway Dashboard → Variables

# =================================
# ✅ CRITICAL - MUST SET FIRST
# =================================

# 1. Database (Auto-generated by Railway PostgreSQL plugin)
DATABASE_URL=postgresql://username:password@host:port/database

# 2. Stripe Payment Processing
STRIPE_SECRET_KEY=sk_live_51...
STRIPE_PUBLISHABLE_KEY=pk_live_51...
STRIPE_WEBHOOK_SECRET=whsec_...

# 3. Stripe Product Price IDs (Create these in Stripe Dashboard first)
STRIPE_BASIC_WEEKLY_PRICE_ID=price_1Rg6fnJF6bibA8nesbJ1RvxA
STRIPE_PRO_WEEKLY_PRICE_ID=price_1Rtf6CJF6bibA8nef9w5LhLE
STRIPE_PRO_ANNUAL_PRICE_ID=price_1Rtf9YJF6bibA8nemK14siZ5

# 4. Firebase Authentication
FIREBASE_PROJECT_ID=your-production-project-id

# Option 1: GOOGLE_CREDENTIALS (Recommended)
GOOGLE_CREDENTIALS={"type":"service_account","project_id":"your-production-project-id","private_key_id":"...","private_key":"-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-xxxxx@your-project.iam.gserviceaccount.com",...}

# Option 2: Individual Variables (Alternative)
FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nYOUR_MULTI_LINE_KEY_HERE\n-----END PRIVATE KEY-----\n"
FIREBASE_CLIENT_EMAIL=firebase-adminsdk-xxxxx@your-project.iam.gserviceaccount.com

# 5. Application Security
NODE_ENV=production
SESSION_SECRET=your-32-character-minimum-secure-random-string

# 6. Storage Configuration
STORAGE_PATH=/app/storage

# =================================
# ✅ FRONTEND CONFIGURATION
# =================================

# React/Vite Build Variables (for client-side)
VITE_FIREBASE_PROJECT_ID=your-production-project-id
VITE_FIREBASE_API_KEY=AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
VITE_FIREBASE_AUTH_DOMAIN=your-project.firebaseapp.com
VITE_FIREBASE_STORAGE_BUCKET=your-project.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=123456789012
VITE_FIREBASE_APP_ID=1:123456789012:web:xxxxxxxxxxxxxxxx
VITE_STRIPE_PUBLISHABLE_KEY=pk_live_51...

# =================================
# 🔧 OPTIONAL - URL OVERRIDES
# =================================

# Only set these if using custom domain
APP_URL=https://your-custom-domain.com
CLIENT_URL=https://your-custom-domain.com

# =================================
# 📊 OPTIONAL - MONITORING
# =================================

# Sentry Error Tracking
SENTRY_DSN=https://xxxxx@o123456.ingest.sentry.io/123456

# Datadog Monitoring
DATADOG_API_KEY=your-datadog-api-key

# New Relic Monitoring
NEW_RELIC_LICENSE_KEY=your-newrelic-license-key

# =================================
# 🚫 DO NOT SET - AUTO PROVIDED
# =================================

# These are automatically set by Railway:
# PORT
# RAILWAY_ENVIRONMENT
# RAILWAY_PROJECT_ID
# RAILWAY_SERVICE_ID
# RAILWAY_DEPLOYMENT_ID
# RAILWAY_REPLICA_ID
# RAILWAY_PUBLIC_DOMAIN
# RAILWAY_PRIVATE_DOMAIN
# RAILWAY_STATIC_URL

# =================================
# 📋 STEP-BY-STEP SETUP GUIDE
# =================================

# 1. STRIPE SETUP:
#    - Go to https://dashboard.stripe.com/apikeys
#    - Copy LIVE keys (not test keys)
#    - Create products with weekly/annual pricing
#    - Note down price IDs

# 2. FIREBASE SETUP:
#    - Go to https://console.firebase.google.com/
#    - Create production project
#    - Enable Authentication → Email/Password
#    - Generate service account key (downloads JSON)
#    - IMPORTANT: Copy private_key from JSON exactly with line breaks
#    - Don't use quotes or \n escape sequences in Railway
#    - Copy project config for frontend

# 3. SESSION SECRET:
#    - Generate: openssl rand -hex 32
#    - Must be 32+ characters

# 4. RAILWAY POSTGRESQL:
#    - Add PostgreSQL plugin in Railway dashboard
#    - DATABASE_URL auto-populated

# 5. WEBHOOK SETUP (after deployment):
#    - Get Railway URL: https://your-app.up.railway.app
#    - Add webhook in Stripe: /api/stripe-webhook
#    - Copy webhook secret to STRIPE_WEBHOOK_SECRET

# =================================
# ✅ VALIDATION COMMANDS
# =================================

# After setting variables, test:
# curl https://your-app.up.railway.app/health
# curl https://your-app.up.railway.app/api/deployment-info

# =================================
# 🚨 SECURITY NOTES
# =================================

# - Use LIVE Stripe keys in production
# - Use production Firebase project
# - Generate unique SESSION_SECRET
# - Never commit secrets to git
# - Firebase private key must include \n newlines
# - All VITE_ variables are PUBLIC (client-side)